version: '3'
services:
  postgres:
    container_name: compassible_postgres
    image: postgres:16.1
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - compassible-postgres:/var/lib/postgresql/data

volumes:
    compassible-postgres: